### PR TITLE
Two small fixes/improvements

### PR DESCRIPTION
**Pull request by fgrsnau**
- corrects behaviour of which/where
- uses execFile instead of exec (important for files containing whitespace)

### CODE REVIEW

**Comment by mattn** [comment]
where command on windows seems to return multiple line. If the code currently is bad, please fix also. (It's my bug)

**Comment by fgrsnau** [comment]
I’m not a Windows user, but I can check. It’s just that I’m a little bit busy right now. So, expect some delay ;-)

**Comment by oxo42** [comment]
If you merge this branch into master, I'll pick up any windows issues

**Comment by oxo42** [comment]
Just tested the changes from @fgrsnau and they work perfectly on Windows, including paths with spaces in them.  I'd say publish this build

**Pull request merged**
